theme = "gruvbox_light"

[editor]
bufferline = "multiple"
line-number = "relative"
text-width = 120

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
